CREATE DATABASE IF NOT EXISTS mpwar;

USE mpwar;

DROP TABLE user;

CREATE TABLE user (
  id INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(40) NOT NULL,
  password VARCHAR(255) NOT NULL
);