---
services:
  - name: "router"
    class: "\\Mpwarfwk\\Component\\Router\\Router"
    arguments:
    - "@parser"
    - "/var/www/html/Mpwar16App/app/routing.yml"
    - "@router_profiler"
    tags:
    public: true
    singleton: false
  - name: "parser"
    class: "\\Mpwarfwk\\Component\\Parser\\YAMLParser"
    arguments:
    tags:
    public: false
    singleton: false
  - name: "twig_templating"
    class: "\\Mpwarfwk\\Component\\Templating\\TwigTemplating"
    arguments:
    tags:
    public: true
    singleton: false
  - name: "smarty_templating"
    class: "\\Mpwarfwk\\Component\\Templating\\SmartyTemplating"
    arguments:
    tags:
    public: true
    singleton: true
  - name: "database_pdo"
    class: "\\Mpwarfwk\\Component\\Database\\Db"
    arguments:
    - {host: localhost, db_name: mpwar, username: root, password: vagrantpass}
    - "@db_profiler"
    tags:
    public: true
    singleton: false
  - name: "db_profiler"
    class: "\\Mpwarfwk\\Component\\Database\\DBProfiler"
    arguments:
    tags:
    - profiling
    public: true
    singleton: true
  - name: "router_profiler"
    class: "\\Mpwarfwk\\Component\\Router\\RouterProfiler"
    arguments:
    tags:
    - profiling
    public: true
    singleton: true